
spring.application.name=todo-app-backend

spring.datasource.url=jdbc:postgresql://ep-patient-cake-am2l006y-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sCl7ISX6ZeKf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=BU4d+LEOEGFJ0/OkCQ9znp+R/NXVqCTigUdaERtVzoE=
jwt.expiration=86400000
